server.port=8080
spring.application.name=demo
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:47.109.145.198}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:homework}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:chenjianyang}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
mybatis.configuration.map-underscore-to-camel-case=true
app.flyway.repair-on-start=false
vision.provider=qwen
vision.qwen.base-url=https://dashscope.aliyuncs.com
vision.qwen.api-key=sk-2ec3046b56534120aee1282a3229a3b6
vision.qwen.vl-model=qwen-vl-plus-latest
vision.qwen.tts-model=qwen-tts
vision.qwen.tts-voice=Cherry
vision.qwen.tts-format=mp3
